import{a as h,S as y,i as n}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const b="46731834-56edab6cfae067b8e4143ec91",L="https://pixabay.com/api/",g=async(r,t)=>{const s=`${L}?key=${b}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;return(await h.get(s)).data.hits},p=r=>{const t=document.querySelector(".gallery"),s=r.map(e=>`
        <div class="photo-card">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${e.likes}</p>
            <p class="info-item"><b>Views:</b> ${e.views}</p>
            <p class="info-item"><b>Comments:</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
      `).join("");t.insertAdjacentHTML("beforeend",s),new y(".gallery a").refresh()},m=document.querySelector("#search-form"),c=document.querySelector(".loader"),f=document.querySelector(".gallery"),l=document.getElementById("load-more");let d=1,a="";m.addEventListener("submit",async r=>{if(r.preventDefault(),a=m.elements.query.value.trim(),d=1,a===""){n.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}c.classList.remove("hidden"),f.innerHTML="";try{const t=await g(a,d);p(t),t.length>0?l.classList.remove("hidden"):(n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.classList.add("hidden"))}catch(t){console.error(t),n.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}finally{c.classList.add("hidden"),m.elements.query.value=""}});l.addEventListener("click",async()=>{d+=1,c.classList.remove("hidden");try{const r=await g(a,d);p(r);const t=f.getBoundingClientRect();if(console.log(t),r.length===0)l.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{const s=document.querySelector(".photo-card");if(s){const i=s.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}}catch(r){console.error(r),n.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}finally{c.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
