import{a as y,S as b,i}from"./assets/vendor-Qob_5Ba8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&t(h)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const L="46731834-56edab6cfae067b8e4143ec91",v="https://pixabay.com/api/",g=async(o,e)=>{const a=`${v}?key=${L}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=15`;try{const t=await y.get(a);return{totalHits:t.data.totalHits,hits:t.data.hits}}catch(t){throw console.error("Error fetching images:",t.response?t.response.data:t.message),t}},u=o=>{const e=document.querySelector(".gallery"),a=o.map(t=>`
        <div class="photo-card">
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${t.likes}</p>
            <p class="info-item"><b>Views:</b> ${t.views}</p>
            <p class="info-item"><b>Comments:</b> ${t.comments}</p>
            <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
          </div>
        </div>
      `).join("");e.insertAdjacentHTML("beforeend",a)},m=document.querySelector("#search-form"),d=document.querySelector(".loader"),w=document.querySelector(".gallery"),n=document.getElementById("load-more");let c=1,l="",f=0;const E=15,p=new b(".gallery a"),P=()=>{const o=document.querySelector(".photo-card");if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}};m.addEventListener("submit",async o=>{if(o.preventDefault(),l=m.elements.query.value.trim(),c=1,l===""){i.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}d.classList.remove("hidden"),w.innerHTML="";try{const{totalHits:e,hits:a}=await g(l,c);f=e,u(a),a.length>0?(n.classList.remove("hidden"),p.refresh()):(i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n.classList.add("hidden"))}catch(e){console.error("Error fetching images on submit:",e),i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{d.classList.add("hidden"),m.elements.query.value=""}});n.addEventListener("click",async()=>{const o=Math.ceil(f/E);if(c>=o){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.classList.add("hidden");return}c+=1,d.classList.remove("hidden");try{const{hits:e}=await g(l,c);u(e),p.refresh(),e.length===0?(i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.classList.add("hidden")):P()}catch(e){console.error("Error fetching images on load more:",e),i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{d.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
