import{a as g,S as h,i}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const y="46731834-56edab6cfae067b8e4143ec91",b="https://pixabay.com/api/",u=async(r,t)=>{const s=`${b}?key=${y}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;return(await g.get(s)).data.hits},f=r=>{const t=document.querySelector(".gallery"),s=r.map(e=>`
        <div class="photo-card">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${e.likes}</p>
            <p class="info-item"><b>Views:</b> ${e.views}</p>
            <p class="info-item"><b>Comments:</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
      `).join("");t.insertAdjacentHTML("beforeend",s),new h(".gallery a").refresh()},p=document.querySelector("#search-form"),c=document.querySelector(".loader"),L=document.querySelector(".gallery"),l=document.getElementById("load-more");let d=1,n="";p.addEventListener("submit",async r=>{if(r.preventDefault(),n=p.elements.query.value.trim(),d=1,n===""){i.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}c.classList.remove("hidden"),L.innerHTML="";try{const t=await u(n,d);f(t),t.length>0?l.classList.remove("hidden"):(i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.classList.add("hidden"))}catch(t){console.error(t),i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}finally{c.classList.add("hidden"),p.elements.query.value=""}});l.addEventListener("click",async()=>{d+=1,c.classList.remove("hidden");try{const r=await u(n,d);f(r),r.length===0&&(l.classList.add("hidden"),i.info({title:"Info",message:"We're sorry, there are no more posts to load.",position:"topRight"}))}catch(r){console.error(r),i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}finally{c.classList.add("hidden"),window.scrollBy({top:200,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
